// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza.RepositoryCore.Context;

namespace Pizza.RepositoryCore.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20191103212848_PizzaOrderStats")]
    partial class PizzaOrderStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pizza.RepositoryCore.Model.PizzaOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseType");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("SauceType");

                    b.Property<int>("SizeInCM");

                    b.HasKey("Id");

                    b.ToTable("PizzaOrders");
                });

            modelBuilder.Entity("Pizza.RepositoryCore.Model.PizzaOrderStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseType");

                    b.Property<DateTime>("Created");

                    b.Property<string>("GivenName");

                    b.Property<int>("LastModified");

                    b.Property<string>("OrderFor_SurName");

                    b.Property<string>("SauceType");

                    b.Property<int>("SizeInCM");

                    b.Property<int>("TotalOrders");

                    b.HasKey("Id");

                    b.ToTable("PizzaOrderStats");
                });

            modelBuilder.Entity("Pizza.RepositoryCore.Model.PizzaOrder", b =>
                {
                    b.OwnsOne("Pizza.RepositoryCore.Model.PersonFullName", "OrderFor", b1 =>
                        {
                            b1.Property<Guid>("PizzaOrderId");

                            b1.Property<DateTime>("Created");

                            b1.Property<string>("GivenName")
                                .HasColumnName("GivenName");

                            b1.Property<DateTime>("LastModified");

                            b1.Property<string>("SurName");

                            b1.HasKey("PizzaOrderId");

                            b1.ToTable("PizzaOrders");

                            b1.HasOne("Pizza.RepositoryCore.Model.PizzaOrder")
                                .WithOne("OrderFor")
                                .HasForeignKey("Pizza.RepositoryCore.Model.PersonFullName", "PizzaOrderId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
